name: To test run the action
on:
  push:
    branches:
      - main

jobs:
  run-action:
    name: Hello Action
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "npm"
          cache-dependency-path: "package-lock.json"

      - name: Install dependency
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run my action
        run: .
